(()=>{
 const album=document.body.dataset.slug||new URLSearchParams(location.search).get('slug');
 const grid=document.getElementById('photos');if(!album||!grid)return;
 const storage='yk-selections:'+album;let selected=new Set();try{selected=new Set(JSON.parse(localStorage.getItem(storage)||'[]'))}catch{}
 const style=document.createElement('style');style.textContent='.yk-select-card{position:relative;min-width:0}.yk-select-card>.photo{width:100%;height:100%}.yk-pick{position:absolute;top:10px;right:10px;z-index:2;background:#111d;color:white;border:1px solid #fff8;border-radius:20px;padding:8px;cursor:pointer}.yk-selections{margin:24px 0;padding:20px;border:1px solid #8885;border-radius:16px}.yk-selections input,.yk-selections textarea{display:block;width:100%;max-width:480px;padding:12px;margin:8px 0 14px;background:#171b22;color:white;border:1px solid #777;border-radius:8px}.yk-selections button{cursor:pointer;padding:12px 18px;border-radius:20px}.yk-trap{display:none}';document.head.append(style);
 const box=document.createElement('section');box.className='yk-selections';box.innerHTML='<h2>Choose your favorites</h2><p>Tap Select on photos, then send your choices to Yevin. This does not unlock original downloads.</p><details><summary id="yk-count">Your selection</summary><form><label>Your name<input name="name" maxlength="100" required autocomplete="name"></label><label>Email or contact detail<input name="contact" maxlength="200" required autocomplete="email"></label><label>Note (optional)<textarea name="note" maxlength="2000"></textarea></label><label class="yk-trap" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><button type="submit">Send selection</button><p role="status" id="yk-result"></p></form></details>';grid.before(box);
 function update(){box.querySelector('#yk-count').textContent=`Review & send ${selected.size} selected photos`;try{localStorage.setItem(storage,JSON.stringify([...selected]))}catch{}}
 grid.querySelectorAll('button.photo').forEach(photo=>{const image=photo.querySelector('img'),id=image?.getAttribute('src')?.split('/').pop().replace(/\.jpg$/i,'');if(!id)return;const wrap=document.createElement('div');wrap.className='yk-select-card';photo.before(wrap);wrap.append(photo);const pick=document.createElement('button');pick.className='yk-pick';pick.type='button';const refresh=()=>{pick.textContent=selected.has(id)?'♥ Selected':'♡ Select';pick.setAttribute('aria-pressed',String(selected.has(id)));pick.setAttribute('aria-label',`Select photo ${id}`)};pick.onclick=()=>{selected.has(id)?selected.delete(id):selected.add(id);refresh();update()};refresh();wrap.append(pick)});update();
 const form=box.querySelector('form');form.method='POST';form.action='https://immich-photos.tail81707f.ts.net/originals/selections';form.target='_blank';
 for(const name of ['album','photos']){const input=document.createElement('input');input.type='hidden';input.name=name;form.append(input)}
 form.onsubmit=event=>{const result=box.querySelector('#yk-result');if(!selected.size){event.preventDefault();result.textContent='Select at least one photo first.';return}form.elements.album.value=album;form.elements.photos.value=JSON.stringify([...selected]);result.textContent='Check the confirmation in the new tab. Your choices remain saved here.'};
})();
